version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pesenin-api
    environment:
      NODE_ENV: production
      DATABASE_URL: file:./dev.db
      JWT_SECRET: ${JWT_SECRET:-production-secret-change-this}
      JWT_EXPIRES_IN: 7d
      PORT: 3000
      CORS_ORIGIN: http://localhost:5173
      LOG_LEVEL: info
    ports:
      - '3000:3000'
    command: >
      sh -c "
        npx prisma db push &&
        node dist/index.js
      "
    restart: unless-stopped