version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pesenin-api-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: file:./dev.db
      JWT_SECRET: dev-secret-change
      JWT_EXPIRES_IN: 7d
      PORT: 3000
      CORS_ORIGIN: http://localhost:5173
      LOG_LEVEL: debug
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma db push && npm run dev"